version: '3.4'
services:
    db:
        image: mysql:5.7
        container_name: restaurant_db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restaurant
        ports:
          - "3307:3306"
    restaurant:
        build: .
        image: restaurant
        container_name: restaurant_app
        restart: always
        environment:
            DB_IP: 127.0.0.1
            DB_PORT: 3307
            DB_USER: root
            DB_PASS: root
            DB_NAME: restaurant
        ports:
            - "8089:8089"
        depends_on:
            - db
