version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: echo "Start building restaurant repo"
      - run: ls
      - run: mvn install -Dmaven.test.skip=true
      
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn test
      
workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
